services:
  app:
    build:
      context: ./Docker
      dockerfile: App.dockerfile
    image: laravelapp-php
    container_name: laravelapp-php
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - 9000:9000
      - 9050:9050
    volumes:
      - ./Source:/var/www
      - ./Docker/PHPDockerFiles/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - LaravelAppNet
    environment:
      - "DB_HOST=db"
      - "DB_PORT=3306"
      - "DB_DATABASE=laravel"
      - "DB_USERNAME=root"
      - "DB_PASSWORD=root"
      - "AppEnvironment=DEV"

  nginx:
    image: nginx:alpine
    container_name: laravelapp-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./Source:/var/www
      - ./Docker/NginxDockerFiles/app.conf:/etc/nginx/conf.d/default.conf
    networks:
      - LaravelAppNet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://laravel/"]
      interval: 30s
      timeout: 20s
      retries: 3

  db:
    image: mysql:5.7
    container_name: laravelapp-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    networks:
      - LaravelAppNet
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 60s
      timeout: 20s
      retries: 3


networks:
  LaravelAppNet:
    driver: bridge

volumes:
  dbdata:
    driver: local
